name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  workflow:
    uses: releaseband/cicd/.github/workflows/release-monorepo.yml@main
    with:
      release_type: node
    secrets: inherit
