name: Validate

on:
  pull_request:
  workflow_dispatch:

env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  workflow:
    uses: releaseband/cicd/.github/workflows/pnpm-validate.yml@main
    secrets: inherit
